import type { Capability, CapabilityId } from '@/types/capability';

export const capabilityRegistry: Capability[] = [
  {
    id: 'search_information',
    name: '信息检索',
    description: '补齐用户当前缺少的外部资料、样本和事实信息。',
    category: 'research',
    defaultExecutorId: 'manual_context_only',
    availableExecutorIds: ['manual_context_only', 'search_api'],
    currentStatus: 'simulated',
    requiresUserInput: true,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: false,
  },
  {
    id: 'analyze_file',
    name: '文件分析',
    description: '分析简历、作品、文档或表格等用户已有材料。',
    category: 'analysis',
    defaultExecutorId: 'not_available_yet',
    availableExecutorIds: ['not_available_yet', 'pdf_parser', 'docx_parser'],
    currentStatus: 'unavailable',
    requiresUserInput: true,
    requiresAuthorization: false,
    requiresFileUpload: true,
    canRunAutomatically: false,
  },
  {
    id: 'generate_learning_plan',
    name: '学习计划生成',
    description: '把能力学习拆成阶段、练习节奏和今日训练。',
    category: 'planning',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_exercises',
    name: '练习材料生成',
    description: '生成题目、训练动作和复盘记录方式。',
    category: 'generation',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_explanation',
    name: '解释材料生成',
    description: '解释概念、错误原因、操作逻辑和判断依据。',
    category: 'generation',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_document',
    name: '文档结构生成',
    description: '生成报告、介绍页、简历段落、方案等文档骨架。',
    category: 'generation',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation', 'word_exporter', 'pdf_exporter'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_table',
    name: '表格/记录表生成',
    description: '生成对比表、复盘表、执行表和反馈记录表。',
    category: 'generation',
    defaultExecutorId: 'markdown_table_generator',
    availableExecutorIds: ['markdown_table_generator', 'excel_exporter'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_workflow',
    name: '工作流拆解',
    description: '把重复任务拆成输入、处理、检查、输出和复用规则。',
    category: 'planning',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_prompt_template',
    name: '提示词模板生成',
    description: '生成可复用的提示词和输入约束。',
    category: 'generation',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_checklist',
    name: '执行清单生成',
    description: '生成用户今天照着做和检查的步骤清单。',
    category: 'planning',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_review_form',
    name: '反馈表生成',
    description: '生成行动后记录结果、卡点和下一步判断的问题。',
    category: 'feedback',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: true,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: false,
  },
  {
    id: 'compare_options',
    name: '选项比较',
    description: '把多个选择放到同一标准下比较，找出关键未知。',
    category: 'analysis',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'generate_message_template',
    name: '沟通话术生成',
    description: '生成联系真实对象、获取反馈或验证需求的话术。',
    category: 'generation',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: false,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: true,
  },
  {
    id: 'track_task',
    name: '任务追踪',
    description: '展示今日任务并记录用户是否执行、执行结果如何。',
    category: 'tracking',
    defaultExecutorId: 'page_task_display',
    availableExecutorIds: ['page_task_display', 'calendar_api', 'notification_system'],
    currentStatus: 'available',
    requiresUserInput: true,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: false,
  },
  {
    id: 'update_plan_from_feedback',
    name: '反馈后调整',
    description: '根据用户反馈更新判断、任务和下一步材料。',
    category: 'feedback',
    defaultExecutorId: 'deepseek_text_generation',
    availableExecutorIds: ['deepseek_text_generation'],
    currentStatus: 'simulated',
    requiresUserInput: true,
    requiresAuthorization: false,
    requiresFileUpload: false,
    canRunAutomatically: false,
  },
];

export function getCapabilityById(id: CapabilityId): Capability {
  return capabilityRegistry.find(capability => capability.id === id)
    || capabilityRegistry.find(capability => capability.id === 'generate_checklist')!;
}
